//Scripted

//Declarative

pipeline {
	agent any
	stages {
		stage ('Build'){
			steps {
				echo "Build"
			}
		}
			stage ('Test'){
			steps {
				echo "Test"
			}
		}
			stage ('Int Test'){
			steps {
				echo "Int Test"
			}
		}
	} 
	post {
		always{
			echo 'I am awsome, I run always'
		}
		success {
			echo 'I run when you are successful'
		}
		failure {
			echo 'I run when you fail'
		}
	}
}