//Scripted

//Declarative

pipeline {
	agent any
	//agent { docker { image 'maven:3.6.3' } }
	//agent { docker { image 'node:13.8' } }
	environment {
		dockerHome = tool 'myDocker'
		mavenHome = tool 'mymaven'
		//PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"

	}
	stages {
		stage ('Checkout') {
			steps {
				//echo "$dockerHome >> test"
				//echo "$mavenHome"
				sh 'mvn --version'
				sh 'docker --version'
				echo "Build"
				echo "PATH  -  $PATH"
				echo "BUILD_NUMBER  -  $env.BUILD_NUMBER"
				echo "BUILD_ID  -  $env.BUILD_ID"
				echo "JOB_NAME  -  $env.JOB_NAME"
				echo "BUILD_TAG  -  $env.BUILD_TAG"
				echo "BUILD_URL  -  $env.BUILD_URL"
			}
		}
		stage ('Compile'){
			steps {
				sh "cd jenkins/currency-exchange-microservice;mvn clean compile"
			}
		}
			stage ('Test'){
			steps {
				sh "cd jenkins/currency-exchange-microservice;mvn test"
			}
		}
			stage ('Integration Test'){
			steps {
				sh "cd jenkins/currency-exchange-microservice;mvn failsafe:integration-test failsafe:verify"
			}
		}
		stage ('Package'){
			steps {
				sh "cd jenkins/currency-exchange-microservice;mvn package -DskipTests"
			}
		}
		stage ('Build Docker Image'){
            steps {
                //"docker build -t iinnapavan/currency-exchange:$env.BUILD_TAG"
                script {
                    dockerImage = docker.build("./jenkins/currency-exchange-microservice/Dockerfile")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub') {
                        dockerImage.push();
                        dockerImage.push('latest');
                    }
                }
            }
        }
	} 
	post {
		always{
			echo 'I am awsome, I run always'
		}
		success {
			echo 'I run when you are successful'
		}
		failure {
			echo 'I run when you fail'
		}
	}
}