//Scripted

//Declarative

pipeline {
	//agent any
	//agent { docker { image 'maven:3.6.3' } }
	agent { docker { image 'node:13.8' } }
	stages {
		stage ('Build'){
			steps {
				//sh 'mvn --version'
				sh 'node --version'
				echo "Build"
			}
		}
			stage ('Test'){
			steps {
				echo "Test"
			}
		}
			stage ('Int Test'){
			steps {
				echo "Int Test"
			}
		}
	} 
	post {
		always{
			echo 'I am awsome, I run always'
		}
		success {
			echo 'I run when you are successful'
		}
		failure {
			echo 'I run when you fail'
		}
	}
}